2024-05-05 03:46:41 INFO     python dataset was loaded successfully
Traceback (most recent call last):
  File "/home/lanz/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1128, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/lanz/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 825, in __getitem__
    raise KeyError(key)
KeyError: 'starcoder2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lnet/work/people/lanz/resq/JB_tasks/code_completion/run_experiment.py", line 78, in <module>
    main(args)
  File "/lnet/work/people/lanz/resq/JB_tasks/code_completion/run_experiment.py", line 54, in main
    model = MODELS[args.model](1) # ToDo Remove lambda x and the random parameter 1
  File "/lnet/work/people/lanz/resq/JB_tasks/code_completion/run_experiment.py", line 32, in <lambda>
    "starcoder2": lambda x: LLMWrapper("../../models/starcoder2-3b")
  File "/lnet/work/people/lanz/resq/JB_tasks/code_completion/src/llm_models.py", line 11, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="auto")
  File "/home/lanz/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/home/lanz/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1130, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `starcoder2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
slurmstepd: error: common_file_write_uint32s: write pid 467167 to /sys/fs/cgroup/cgroup.procs failed: Device or resource busy
slurmstepd: error: Unable to move pid 467167 to init root cgroup /sys/fs/cgroup
slurmstepd: error: error unlocking cgroup '/sys/fs/cgroup/system.slice/slurmstepd.scope' : Bad file descriptor
